# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a556031e8a54b39c2ccb91895fd1045b"
name = "image-captioner"
application_url = "https://f28c-2605-59c8-30dc-ae10-d86d-8c00-de4b-8373.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "image-captioner-testing.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,read_products,write_products"

[auth]
redirect_urls = [
  "https://f28c-2605-59c8-30dc-ae10-d86d-8c00-de4b-8373.ngrok-free.app/auth/callback",
  "https://f28c-2605-59c8-30dc-ae10-d86d-8c00-de4b-8373.ngrok-free.app/auth/shopify/callback",
  "https://f28c-2605-59c8-30dc-ae10-d86d-8c00-de4b-8373.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
